language: java

dist: bionic

cache:
  directories:
  - apache-ant-1.10.6 

before_install:
    - sudo apt-get update
    - sudo apt-get install -y xmlstarlet
    - if [ -d "apache-ant-1.10.6" ]; then echo "Ant already downloaded..."; fi
    - if [ ! -d "apache-ant-1.10.6" ]; then echo "Downloading ant..."; wget https://www.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.tar.gz; tar -xzvf apache-ant-1.10.6-bin.tar.gz; fi
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)

install:
    - ant -diagnostics
    - free -m

script:
    - xmlstarlet val -e -s xsd/eml.xsd src/test/resources/eml-sample.xml
    - ant test
