language: java

dist: bionic

before_install:
    - sudo apt-get update
    - sudo apt-get install -y xmlstarlet
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.tar.gz
    - tar -xzvf apache-ant-1.10.6-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)

install:
    - ant -diagnostics
    - free -m

script:
    - xmlstarlet val -e -s xsd/eml.xsd src/test/resources/eml-sample.xml
    - ant test
