language: java

dist: bionic

before-install:
    - sudo apt-get update
    - sudo apt-get install -y xmlstarlet ant ant-optional

install:
    - ant -diagnostics
    - free -m

script:
    - xmlstarlet val -e -s xsd/eml.xsd src/test/resources/eml-sample.xml
    - ant test
