language: java

addons:
  apt:
    packages:
    - xmlstarlet
    - ant
    - ant-optional

script:
    - free -m
    - xmlstarlet val -e -s xsd/eml.xsd src/test/resources/eml-sample.xml
    - ant -diagnostics
    - ANT_OPTS=-Xmx2G ant test
